# 端口配置
server:
  port: 8800
  tomcat:
    max-http-form-post-size: 20MB

spring:
  # JSON配置
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
  # 最大文件大小配置
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  # 应用程序名
  application:
    name: find-me-image
  cloud:
    # Consul配置
    consul:
      host: "127.0.0.1"
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
        prefer-ip-address: true
        # ip-address: "服务器外网地址"
  # MongoDB配置
  data:
    mongodb:
      host: "127.0.0.1"
      port: 27017
      database: "find_me"
      # username: "用户名"
      # password: "密码"
      authentication-database: "admin"