# 端口配置
server:
  port: 8800
  tomcat:
    max-http-form-post-size: 20MB

# 应用程序名
spring:
  application:
    name: find-me-gateway
  # Redis
  data:
    redis:
      host: "127.0.0.1"
      port: 6379
  #      password: "密码"
  cloud:
    # Consul配置
    consul:
      host: "127.0.0.1"
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
    # 注册到注册中心
    gateway:
      discovery:
        locator:
          enabled: true
      # 路由转发部分
      routes:
        # 图片服务
        - id: "image"
          uri: "lb://find-me-image"
          predicates:
            - "Path=/api/image/**"
        # 会话服务
        - id: "session"
          uri: "lb://find-me-session"
          predicates:
            - "Path=/api/session/**"
        # 会话服务-WebSocket
        - id: "session-ws"
          uri: "lb:ws://find-me-session"
          predicates:
            - "Path=/ws/session/**"
        # 用户服务
        - id: "user"
          uri: "lb://find-me-user"
          predicates:
            - "Path=/api/user/**"