# 端口配置
server:
  port: 8800
  tomcat:
    max-http-form-post-size: 20MB

# 应用程序名
spring:
  application:
    name: find-me-gateway
  cloud:
    # Nacos配置
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # 注册到注册中心
    gateway:
      discovery:
        locator:
          enabled: true
      # 路由转发部分
      routes:
        # 图片服务
        - id: "image"
          uri: "lb://find-me-image"
          predicates:
            - Path=/api/image/avatar/**