# 端口配置
server:
  port: 8800
  tomcat:
    max-http-form-post-size: 20MB

# 应用程序名
spring:
  application:
    name: find-me-gateway
  # Redis
  data:
    redis:
      host: "127.0.0.1"
      port: 6379
      # password: "密码"
  cloud:
    # Consul配置
    consul:
      host: "127.0.0.1"
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}-${spring.cloud.client.hostname}-${server.port}
        heartbeat:
          enabled: true
        prefer-ip-address: true
        # ip-address: "服务器外网地址"
    # 注册到注册中心
    gateway:
      discovery:
        locator:
          enabled: true
      # 路由转发部分
      routes:
        # 会话服务
        - id: "session"
          uri: "lb://find-me-session"
          predicates:
            - "Path=/api/session/**"
        # 会话服务-WebSocket
        - id: "session-ws"
          uri: "lb:ws://find-me-session"
          predicates:
            - "Path=/ws/session/**"
        # 用户服务
        - id: "user"
          uri: "lb://find-me-user"
          predicates:
            - "Path=/api/user/**"

# Sa-Token配置
sa-token:
  token-name: "findme-satoken"
  is-concurrent: false
  is-share: true
  token-style: simple-uuid
  is-log: false

# 自定义配置
com:
  gitee:
    swsk33:
      bean-config:
        config-redis-serde: false