services:
  # Nginx反向代理
  find-me-nginx:
    image: swsk33/find-me-web
    volumes:
      - find-me-nginx-config:/etc/nginx
    ports:
      - 80:80
      - 443:443
    links:
      - find-me-gateway
  # 网关
  find-me-gateway:
    image: swsk33/find-me-gateway
    environment:
      - CONSUL_HOST=consul
      - REDIS_HOST=redis
    links:
      - consul
      - redis
  # 用户模块
  find-me-user:
    image: swsk33/find-me-user
    environment:
      - CONSUL_HOST=consul
      - REDIS_HOST=redis
      - MONGO_HOST=mongodb
      # 邮箱配置（需要自己填一下）
      - EMAIL_SMTP_HOST=smtp.163.com
      - EMAIL_USER=你的邮箱
      - EMAIL_PASSWORD=授权码
    links:
      - consul
      - mongodb
      - redis
  # 会话模块
  find-me-session:
    image: swsk33/find-me-session
    environment:
      - CONSUL_HOST=consul
      - REDIS_HOST=redis
      - MONGO_HOST=mongodb
      - KAFKA_URL=kafka:9092
    links:
      - consul
      - redis
      - mongodb
      - kafka
  # Consul注册中心
  consul:
    image: consul
    command: agent -server -ui -node=find-me-node -bootstrap-expect=1 -client=0.0.0.0
  # MongoDB数据库
  mongodb:
    image: mongo
    volumes:
      - find-me-mongodb-data:/data/db
  # Redis数据库
  redis:
    image: redis
    volumes:
      - find-me-redis-data:/data
  # Kafka消息中间件
  kafka:
    image: swsk33/kafka-standalone
    environment:
      - CLUSTER_ID=YWJjZGVmZ2hpamtsbW5vcA==
      - KAFKA_HOST=kafka

volumes:
  find-me-nginx-config:
  find-me-mongodb-data:
  find-me-redis-data:
