# 端口配置
server:
  port: 8800
  tomcat:
    max-http-form-post-size: 20MB

spring:
  # 最大文件大小配置
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  # JSON配置
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
  # 应用程序名
  application:
    name: find-me-user
  cloud:
    # Consul配置
    consul:
      host: "127.0.0.1"
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}-${spring.cloud.client.hostname}-${server.port}
        heartbeat:
          enabled: true
        prefer-ip-address: true
        # ip-address: "服务器外网地址"
  data:
    # MongoDB配置
    mongodb:
      host: "127.0.0.1"
      port: 27017
      database: "find_me"
      # username: "用户名"
      # password: "密码"
      authentication-database: "admin"
    # Redis配置
    redis:
      host: "127.0.0.1"
      port: 6379
      # password: "密码"

io:
  github:
    swsk33:
      # 文件上传配置
      file-lift:
        core:
          storage-method: "mongodb"
          size-limit: 5120
          auto-rename-format: "snow_flake"
          allowed-formats:
            - "jpg"
            - "jpeg"
            - "png"
            - "gif"
            - "bmp"
      # 邮件验证码配置
      code-post:
        core:
          smtp-host: "smtp.163.com"
          email: "你的邮箱"
          password: "你的邮箱密码（或者是授权码）"
          code-storage: "redis"
          site-name: "FindMe"

# Sa-Token配置
sa-token:
  token-name: "findme-satoken"
  is-concurrent: false
  is-share: true
  token-style: simple-uuid
  is-log: false