# 端口配置
server:
  port: 8800
  tomcat:
    max-http-form-post-size: 20MB

spring:
  # JSON配置
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
  # 应用程序名
  application:
    name: find-me-user
  # 邮箱配置
  mail:
    host: "smtp.163.com"
    username: ""
    password: ""
    default-encoding: "UTF-8"
    properties:
      "[mail.smtp.socketFactory.class]": "javax.net.ssl.SSLSocketFactory"
      "[mail.smtp.socketFactory.port]": 465
      "[mail.smtp.auth]": true
      "[mail.smtp.starttls.enable]": true
      "[mail.smtp.starttls.required]": true
  cloud:
    # Consul配置
    consul:
      host: "127.0.0.1"
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
        prefer-ip-address: true
        # ip-address: "服务器外网地址"
  data:
    # MongoDB配置
    mongodb:
      host: "127.0.0.1"
      port: 27017
      database: "find_me"
      # username: "用户名"
      # password: "密码"
      authentication-database: "admin"
    # Redis配置
    redis:
      host: "127.0.0.1"
      port: 6379
      # password: "密码"

# Sa-Token配置
sa-token:
  token-name: "findme-satoken"
  is-concurrent: false
  is-share: true
  token-style: simple-uuid
  is-log: false